### ISSUE TITLE
Wait for termination of netty on Transport.stop()

### ISSUE THREAD

**Issue by camann9** [Graylog2/gelfclient#12]
Currently the AbstractGelfTransport.stop() method doesn't wait for the returned future to terminate before returning. It would be desirable to block during netty termination or to offer another stop method that is blocking (or to return the future). Example for blocking shutdown:

    workerGroup.shutdownGracefully()..awaitUninterruptibly()

**Comment by bernd** [comment]
Thanks for the heads up!
