### ISSUE TITLE
Guarantee that message was delivered to Graylog

### ISSUE THREAD

**Issue by kadledav** [Graylog2/gelfclient#21]
In our company we are using gelfclient from many different geographical locations for appending to Graylog. Everything works fine until some client lost its connection for a while. When the client is temporarily disconnected we lost some logs which we would like to receive. Can you give us an advice how to use your client properly to avoid those situations? 

I look at your code to the class org.graylog2.gelfclient.transport.GelfSenderThread and I think the problem is when the gelfMessage is written to channel without processing a returned future. Is it possible to improve the gelfclient so it will not lose messages when there will be problem with the connection?

**Comment by ralberto** [comment]
+1

**Comment by joschi** [comment]
The GELF protocol doesn't support ACKs or any other form of message delivery guarantee. Thus, gelfclient also can't make those guarantees.

We might revisit this if (or when) we drafted the next version of the GELF protocol, but for now I'll close this issue.
