### ISSUE TITLE
Sending 2mil messages causes out of memory error

### ISSUE THREAD

**Issue by kadledav** [Graylog2/gelfclient#22]
I encountered a problem when I tried to send a lot of messages with fixed heap size. By a lot of I mean that I'm unable to load them all to java memory at once. I'm reading messages from a file and I'm using org.graylog2.gelfclient.transport.GelfTransport#send blocking method which use blocking queue. But the problem is that the blocking queue is never full because GelfSenderThread drains messages to Netty channel.writeAndFlush without waiting for response. So effectively the blocking queue is drained to Netty WriteAndFlushTask queue. And thats the place where all the messages are accumulated which cause the out of memory.  
 
I would expect that org.graylog2.gelfclient.transport.GelfTransport#send method would block me until some messages are successfully sent (they are processed from Netty internal queue).  

I have attached sample app to this issue which demonstrates the problem. Don't forget run it with java parameter -Xmx256m

**Comment by kadledav** [comment]
I couldn't attach zip file directly so here is dropbox link
https://www.dropbox.com/s/kepacn3y2oxyhpl/gelfclientBug.zip?dl=1

**Comment by kroepke** [comment]
I've pushed the code up to github for easier reproduction (which I haven't done yet)

**Comment by bernd** [comment]
@kadledav Thanks for the report that the code to reproduce. The issue will be fixed in the upcoming 1.4.0 release.
