### ISSUE TITLE
Client produces incompatible JSON

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/gelfclient#27]
The timestamp value is being serialized to, for example, this:

```
1.497313808264E9
```

Graylog does not work with the scientific notation and rejects the message.

Environment:

```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by lennartkoopmann** [comment]
The tests don't catch this because they compare two scientific notations, which returns true.

**Comment by joschi** [comment]
@lennartkoopmann `1.497313808264E9` is a valid number in JSON.

Additionally, I couldn't reproduce the issue you've described.

The following GELF message is processed fine by Graylog (GELF UDP input):
```json
{
   "timestamp" : 1.497313808264E9,
   "short_message" : "test",
   "source" : "issue-27",
   "version" : "1.1"
}
```

Sent via netcat:
```
echo '{"version":"1.1","short_message":"test","source":"issue-27", "timestamp":1.497313808264E9}'|nc -w0 -u 127.0.0.1 12201
```

Result (Graylog 2.3.0-alpha.3-SNAPSHOT):
<img width="1188" alt="Message in Graylog" src="https://user-images.githubusercontent.com/43951/27073994-fb63c19e-5025-11e7-8fb2-22e1357649cd.png">

**Comment by lennartkoopmann** [comment]
🤔 🤔 🤔 🤔 🤔 

let me check. thanks already!
