### ISSUE TITLE
GelfClient incurs cost of toString() on each message even when debug logging is not enabled

### ISSUE THREAD

**Issue by agrove-rms** [Graylog2/gelfclient#38]
The method `org.graylog2.gelfclient.transport.AbstractGelfTransport#trySend` contains this logging statement:

```java
LOG.debug("Trying to send message: {}", message.toString());
```

Even if debug logging is disabled, `message.toString()` is still invoked and adds overhead.

I suggest the following:

```java
if (LOG.isDebugEnabled()) {
    LOG.debug("Trying to send message: {}", message.toString());
}
```

I can't create a PR for this due to your requirement of signing a legal document first.

**Comment by agrove-rms** [comment]
On second thoughts, we could just change remove the `.toString()` since it is redundant - the logger will do this anyway (if debug logging is enabled).

```java
LOG.debug("Trying to send message: {}", message.toString());
```

**Comment by joschi** [comment]
@agrove-rms Thanks for reporting this! We'll release a fixed version of gelfclient soon.
