### ISSUE TITLE
Set to crated threads property daemon

### ISSUE THREAD

**Issue by dmytrokarimov** [Graylog2/gelfclient#8]
Set to create threads property 'daemon'
Without it program can't terminated normally

**Comment by dmytrokarimov** [comment]
diff --git a/src/main/java/org/graylog2/gelfclient/transport/AbstractGelfTransport.java b/src/main/java/org/graylog2/gelfclient/transport/AbstractGelfTransport.java
index b377099..f0d5be4 100644
--- a/src/main/java/org/graylog2/gelfclient/transport/AbstractGelfTransport.java
+++ b/src/main/java/org/graylog2/gelfclient/transport/AbstractGelfTransport.java
@@ -18,14 +18,16 @@
 
 import io.netty.channel.EventLoopGroup;
 import io.netty.channel.nio.NioEventLoopGroup;
-import org.graylog2.gelfclient.GelfConfiguration;
-import org.graylog2.gelfclient.GelfMessage;
-import org.slf4j.Logger;
-import org.slf4j.LoggerFactory;
+import io.netty.util.concurrent.DefaultThreadFactory;
 
 import java.util.concurrent.BlockingQueue;
 import java.util.concurrent.LinkedBlockingQueue;
 import java.util.concurrent.TimeUnit;
+
+import org.graylog2.gelfclient.GelfConfiguration;
+import org.graylog2.gelfclient.GelfMessage;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
 
 /**
  * An abstract {@link GelfTransport} implementation serving as parent for the concrete implementations.
@@ -37,7 +39,7 @@
     protected final GelfConfiguration config;
     protected final BlockingQueue<GelfMessage> queue;
 
-    private final EventLoopGroup workerGroup = new NioEventLoopGroup();
+    private final EventLoopGroup workerGroup = new NioEventLoopGroup(0, new DefaultThreadFactory(getClass(), true));
 
     /**
      * Creates a new GELF transport with the given configuration and {@link java.util.concurrent.BlockingQueue}.
diff --git a/src/main/java/org/graylog2/gelfclient/transport/GelfSenderThread.java b/src/main/java/org/graylog2/gelfclient/transport/GelfSenderThread.java
index ae079de..709d80f 100644
--- a/src/main/java/org/graylog2/gelfclient/transport/GelfSenderThread.java
+++ b/src/main/java/org/graylog2/gelfclient/transport/GelfSenderThread.java
@@ -17,15 +17,16 @@
 package org.graylog2.gelfclient.transport;
 
 import io.netty.channel.Channel;
-import org.graylog2.gelfclient.GelfMessage;
-import org.slf4j.Logger;
-import org.slf4j.LoggerFactory;
 
 import java.util.concurrent.BlockingQueue;
 import java.util.concurrent.TimeUnit;
 import java.util.concurrent.atomic.AtomicBoolean;
 import java.util.concurrent.locks.Condition;
 import java.util.concurrent.locks.ReentrantLock;
+
+import org.graylog2.gelfclient.GelfMessage;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
 
 /**
  * The main event thread used by the {@link org.graylog2.gelfclient.transport.GelfTransport}s.
@@ -92,7 +93,9 @@
                 LOG.debug("GelfSenderThread exiting!");
             }
         });
-
+        
+        this.senderThread.setDaemon(true);
+        
         this.senderThread.setName("GelfSenderThread-" + senderThread.getId());
     }

**Comment by bernd** [comment]
Thanks, I will test this.
